server {
    listen 80;
    listen [::]:80;
    server_name environmental-literacy.seasidesustainability.org;

    root /var/www/firesafe-atlas;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
